import { ChevronLeftIcon } from '@heroicons/react/solid';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

import Page from '../../components/Page';
import { posts } from '../../data';

export default function Video() {
  const router = useRouter();
  const { query } = router;

  const [post, setPost] = useState(posts.find((post) => post.slug === query.slug));

  useEffect(() => {
    setPost(posts.find((post) => post.slug === query.slug));
  }, [query.slug]);

  return (
    <Page title="learning-app" description="Generated by Create Next Stack.">
      <div className="relative h-full w-full bg-gray-50 min-h-screen mx-auto py-16">
        <div className="fixed top-0 flex flex-col px-8 py-4 bg-black w-full">
          <div className="flex flex-row items-center gap-x-4 ">
            <div className="bg-gray-50 h-10 w-10 rounded-lg" />
            <div className="flex flex-col flex-1 text-white">
              <p className="text-md">
                Aktivitas <strong>{post?.category.name}</strong>
              </p>
              <p className="text-xs">
                {post?.minAge}-{post?.maxAge} Tahun
              </p>
            </div>
          </div>
          <p className="text-white font-semibold mt-4">{post?.title}</p>
        </div>
        <div className="mt-0 max-w-lg mx-auto grid gap-8 md:max-w-screen-md lg:max-w-screen-xl">
          <img
            className="h-64 w-full object-cover rounded-b-2xl md:h-96"
            src={post?.imageUrl}
            alt=""
          />
        </div>

        <div className="flex flex-col justify-center bg-yellow-300 mt-8 mx-4 pb-24 pt-2 px-2 rounded-xl">
          <div className="bg-yellow-100 w-full p-4 rounded-xl">
            <h2 className="font-medium text-lg">Tujuan Aktivitas</h2>
            <p className="mt-2">{post?.objective}</p>
          </div>
          <div className="mt-4 px-4">
            <h2 className="font-medium">Bahan yang perlu bunda persiapkan</h2>
            <ul className="mt-2">
              {post?.items.map((item) => (
                <li key={item}>
                  <div className="flex flex-row py-1 items-center">
                    <div className="h-4 w-4 mr-2 rounded-full bg-blue-300"></div>
                    <p>{item}</p>
                  </div>
                </li>
              ))}
            </ul>
          </div>
        </div>

        <div className="absolute bottom-0 w-full bg-black rounded-t-xl">
          <button className="p-4 text-white" onClick={() => router.back()}>
            <ChevronLeftIcon className="h-8 w-8" />
          </button>
        </div>
      </div>
    </Page>
  );
}
