import Link from 'next/link';
import { useRouter } from 'next/router';

import Page from '../../../components/Page';
import { posts } from '../../../data';

export default function CategoryIndex() {
  const router = useRouter();
  const { query } = router;

  const [minAge, maxAge] = (query.age as string)?.split('-') || [];

  const displayedPosts = posts.filter(
    (post) =>
      parseInt(maxAge) >= post.minAge &&
      post.maxAge >= parseInt(minAge) &&
      post.category.slug === query.category
  );

  return (
    <Page title="learning-app" description="Generated by Create Next Stack.">
      <div className="relative h-full w-full bg-gray-50 min-h-screen mx-auto py-16">
        <div className="fixed top-0 flex flex-row items-center gap-x-4 px-8 py-4 bg-black w-full">
          <div className="bg-gray-50 h-10 w-10 rounded-lg" />
          <div className="flex flex-col flex-1 text-white">
            <p className="text-md">
              Aktivitas <strong>{query.category}</strong>
            </p>
            <p className="text-xs">{query.age} Tahun</p>
          </div>
        </div>
        {displayedPosts.length > 0 ? (
          <div className="mt-12 max-w-lg mx-auto grid gap-8 md:grid-cols-2 md:max-w-screen-md lg:mt-16 lg:grid-cols-3 lg:max-w-screen-xl">
            {displayedPosts.map((post) => (
              <div
                key={post.slug}
                className="flex flex-col mx-auto rounded-2xl shadow-lg overflow-hidden"
              >
                {post.needRegistration ? (
                  <div className="group relative flex-shrink-0 bg-gradient-to-r from-yellow-300 to-yellow-50">
                    <img
                      className="h-52 w-full object-cover rounded-t-2xl rounded-b-3xl blur-sm brightness-50 md:group-hover:blur-sm md:group-hover:brightness-50"
                      src={post.imageUrl}
                      alt=""
                    />
                    <button className="absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 w-max flex justify-center py-2 px-8 rounded-lg shadow-lg text-xl font-medium text-black bg-yellow-300 hover:bg-yellow-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-yellow-500">
                      Daftar Gratis
                    </button>
                  </div>
                ) : (
                  <Link href={`/video/${post.slug}`}>
                    <a className="flex-shrink-0 bg-gradient-to-r from-yellow-300 to-yellow-50">
                      <img
                        className="h-52 w-full object-cover rounded-t-2xl rounded-b-3xl"
                        src={post.imageUrl}
                        alt=""
                      />
                    </a>
                  </Link>
                )}
                <div className="flex-1 flex flex-row justify-between">
                  <div className="flex px-4 py-2 bg-yellow-300 rounded-br-2xl items-center justify-end">
                    <span className="text-xl font-semibold">{post.minAge}+</span>thn
                  </div>
                  <div className="flex-1 px-4 py-2 bg-yellow-50">
                    <p className="text-sm text-black font-normal">{post.title}</p>
                    <div className="flex flex-row gap-x-4 items-center">
                      <p className="text-xs text-black">
                        <Link href={`/kategori/${post.category.slug}`}>
                          <a className="hover:underline">{post.category.name}</a>
                        </Link>{' '}
                        • {post.numberOfPlay}x dimainkan oleh ibu
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="w-full mt-16 p-8">
            <p className="text-center">Aktivitas belum tersedia</p>
          </div>
        )}
        <div className="flex flex-col justify-center items-center mt-16">
          <p>Daftar untuk lorem ipsum dolor sit</p>
          <button className="w-max flex justify-center mt-4 py-2 px-8 border border-transparent rounded-lg shadow-lg text-xl font-medium text-black bg-yellow-300 hover:bg-yellow-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-yellow-500">
            Daftar Gratis
          </button>
        </div>
      </div>
    </Page>
  );
}
