import { RadioGroup } from '@headlessui/react';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';

import Page from '../components/Page';
import { ageSettings, categories, renderBgColor, renderRingColor } from '../data';
import NafliboxLogo from '../public/images/naflibox-logo.png';
import classNames from '../utils/classNames';

export default function Index() {
  const [selectedAge, setSelectedAge] = useState(ageSettings[0]?.slug);
  const [selectedCategory, setSelectedCategory] = useState(categories[0]?.slug);

  return (
    <Page title="learning-app" description="Generated by Create Next Stack.">
      <div className="relative bg-gray-50 mx-auto max-w-sm h-full min-h-screen">
        <div className="p-4 w-40">
          <Image src={NafliboxLogo} />
        </div>
        <div className="max-w-xs mx-auto py-0">
          <h2 className="text-md mb-4 px-4">Bunda ingin bermain aktifitas umur berapa?</h2>
          <RadioGroup value={selectedAge} onChange={setSelectedAge}>
            <RadioGroup.Label className="sr-only">Age Settings</RadioGroup.Label>
            <div className="bg-white rounded-md space-y-2">
              {ageSettings.map((setting) => (
                <RadioGroup.Option
                  key={setting.name}
                  value={setting.slug}
                  className={({ checked }) =>
                    classNames(
                      checked && 'z-10',
                      'flex relative items-center bg-cyan-400 border-cyan-400 border px-4 py-2 cursor-pointer rounded-2xl focus:outline-none'
                    )
                  }
                >
                  {({ active, checked }) => (
                    <>
                      <span
                        className={classNames(
                          checked ? 'bg-yellow-400 border-yellow-400' : 'bg-white border-gray-300',
                          active ? 'ring-2 ring-offset-2 ring-yellow-400 border-yellow-400' : '',
                          'h-6 w-6 mt-0.5 cursor-pointer rounded-lg border flex items-center justify-center'
                        )}
                        aria-hidden="true"
                      />
                      <div className="w-full ml-3 flex flex-col text-right">
                        <RadioGroup.Label
                          as="span"
                          className="block text-lg text-stone-600 font-semibold"
                        >
                          {setting.name}
                        </RadioGroup.Label>
                      </div>
                    </>
                  )}
                </RadioGroup.Option>
              ))}
            </div>
          </RadioGroup>

          <h2 className="text-md my-4 px-4">Bunda ingin mempelajari kategori apa?</h2>
          <RadioGroup value={selectedCategory} onChange={setSelectedCategory}>
            <RadioGroup.Label className="sr-only">Category</RadioGroup.Label>
            <div className="mx-auto grid grid-cols-3 gap-2">
              {categories.map((category) => (
                <RadioGroup.Option key={category.slug} value={category.slug}>
                  {({ checked }) => (
                    <>
                      <div
                        className={classNames(
                          checked && `ring-4 ${renderRingColor(category.slug)}`,
                          `${renderBgColor(
                            category.slug
                          )} relative w-24 h-24 justify-center border rounded-3xl cursor-pointer sm:flex focus:outline-none`
                        )}
                        aria-hidden="true"
                      >
                        <div className="absolute -left-1 -top-1 w-20 h-20 ">
                          <Image src={category.images} layout="fill" objectFit="contain" />
                        </div>
                      </div>
                      <RadioGroup.Label
                        as="p"
                        className="w-full font-medium text-center text-stone-600 text-md"
                      >
                        {category.name}
                      </RadioGroup.Label>
                    </>
                  )}
                </RadioGroup.Option>
              ))}
            </div>
          </RadioGroup>
        </div>

        <Link href={`/kategori/${selectedCategory}/${selectedAge}`}>
          <a>
            <button className="absolute bottom-2 right-2 w-max flex justify-center mt-4 py-2 px-8 border border-transparent rounded-xl shadow-lg text-xl font-medium text-black bg-yellow-300 hover:bg-yellow-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-yellow-500">
              Pilih ide
            </button>
          </a>
        </Link>
      </div>
    </Page>
  );
}
