import { RadioGroup } from '@headlessui/react';
import Link from 'next/link';
import { useState } from 'react';

import Page from '../components/Page';
import { ageSettings, categories } from '../data';
import classNames from '../utils/classNames';

export default function Index() {
  const [selectedAge, setSelectedAge] = useState(ageSettings[0]?.slug);
  const [selectedCategory, setSelectedCategory] = useState(categories[0]?.slug);

  return (
    <Page title="learning-app" description="Generated by Create Next Stack.">
      <div className="relative bg-gray-50 mx-auto max-w-sm h-full min-h-screen">
        <div className="max-w-xs mx-auto py-8">
          <h2 className="text-2xl mb-8">Bunda ingin bermain aktifitas umur berapa?</h2>
          <RadioGroup value={selectedAge} onChange={setSelectedAge}>
            <RadioGroup.Label className="sr-only">Age Settings</RadioGroup.Label>
            <div className="bg-white rounded-md space-y-2">
              {ageSettings.map((setting) => (
                <RadioGroup.Option
                  key={setting.name}
                  value={setting.slug}
                  className={({ checked }) =>
                    classNames(
                      checked
                        ? 'bg-yellow-300 border-yellow-400 z-10'
                        : 'bg-yellow-100 border-yellow-200',
                      'relative border p-4 flex cursor-pointer rounded-xl focus:outline-none'
                    )
                  }
                >
                  {({ active, checked }) => (
                    <>
                      <span
                        className={classNames(
                          checked ? 'bg-yellow-900 border-transparent' : 'bg-white border-gray-300',
                          active ? 'ring-2 ring-offset-2 ring-yellow-900' : '',
                          'h-4 w-4 mt-0.5 cursor-pointer rounded-md border flex items-center justify-center'
                        )}
                        aria-hidden="true"
                      >
                        <span className="rounded-md bg-white w-1.5 h-1.5" />
                      </span>
                      <div className="w-full ml-3 flex flex-col text-right">
                        <RadioGroup.Label
                          as="span"
                          className={classNames(
                            checked ? 'text-black' : 'text-black',
                            'block text-md font-medium'
                          )}
                        >
                          {setting.name}
                        </RadioGroup.Label>
                      </div>
                    </>
                  )}
                </RadioGroup.Option>
              ))}
            </div>
          </RadioGroup>

          <h2 className="text-2xl my-8">Bunda ingin mempelajari kategori apa?</h2>
          <RadioGroup value={selectedCategory} onChange={setSelectedCategory}>
            <RadioGroup.Label className="sr-only">Category</RadioGroup.Label>
            <div className="mx-auto grid grid-cols-3 gap-4">
              {categories.map((category) => (
                <RadioGroup.Option
                  key={category.slug}
                  value={category.slug}
                  className={({ checked, active }) =>
                    classNames(
                      checked ? 'bg-yellow-300' : 'bg-yellow-100',
                      active ? 'ring-2 ring-yellow-500' : '',
                      'relative flex bg-white justify-center border rounded-lg p-4 cursor-pointer sm:flex focus:outline-none'
                    )
                  }
                >
                  {({ active, checked }) => (
                    <>
                      <div
                        className={classNames(
                          active ? 'ring-2 ring-yellow-500' : '',
                          checked ? 'bg-yellow-300' : 'bg-yellow-100',
                          'absolute -inset-px rounded-lg pointer-events-none'
                        )}
                        aria-hidden="true"
                      />
                      <div className="flex items-center z-10">
                        <RadioGroup.Label as="p" className="font-medium text-black text-md">
                          {category.name}
                        </RadioGroup.Label>
                      </div>
                    </>
                  )}
                </RadioGroup.Option>
              ))}
            </div>
          </RadioGroup>
        </div>

        <Link href={`/kategori/${selectedCategory}/${selectedAge}`}>
          <a>
            <button className="absolute bottom-8 right-8 w-max flex justify-center mt-4 py-2 px-8 border border-transparent rounded-lg shadow-lg text-xl font-medium text-black bg-yellow-300 hover:bg-yellow-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-yellow-500">
              Pilih ide
            </button>
          </a>
        </Link>
      </div>
    </Page>
  );
}
